# 自定义配置，必须放在顶层[]之上，否则读取不到
env = "dev"

[server]
    service_name = "oauth-server"
    port = 8990

[log]
    level = "info"
    logpath = "logs"
    rotate = "hour"
    succ_stat_code = [200, 40000, 50000]

# 数据库
[[database]]
    name = "oauth"
    master = "raapix:StopFuckingAttack!@tcp(erth-public-dev.mysql.rds.aliyuncs.com:3306)/erthvideo?charset=utf8mb4&parseTime=true&loc=Local&readTimeout=10s&max_active=100"
    slaves = ["raapix:StopFuckingAttack!@tcp(erth-public-dev.mysql.rds.aliyuncs.com:3306)/erthvideo?charset=utf8mb4&parseTime=true&loc=Local&readTimeout=3s&max_active=100"]

